CREATE TABLE IF NOT EXISTS thread_invites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    thread_id INT NOT NULL,
    token VARCHAR(32) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;